import com.intellij.ui.DocumentAdapter;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import java.awt.*;
import java.util.concurrent.atomic.AtomicBoolean;

public class GenerateBoardFrame {
    private JLabel titleLabel;
    private JTextField itemTextField;
    private JTextField layoutTextField;
    private JTextField packageTextField;
    private JLabel itemLabel;
    private JLabel layoutLabel;
    private JLabel packageLabel;
    private JPanel groupPanel;
    private AtomicBoolean inUpdate = new AtomicBoolean(true);
    private Boolean itemUpdateFromInput = false;
    private Boolean layoutUpdateFromInput = false;

    public GenerateBoardFrame(String packageName) {
        itemTextField.setText("Item");
        itemTextField.getDocument().addDocumentListener(new DocumentAdapter() {

            @Override
            protected void textChanged(@NotNull DocumentEvent documentEvent) {
                updateLayoutName();
            }
        });

        layoutTextField.getDocument().addDocumentListener(new DocumentAdapter() {
            @Override
            public void textChanged(@NotNull DocumentEvent documentEvent) {
                updateItemName();
            }
        });

        itemTextField.requestFocus();
        itemTextField.setCaretPosition(1);
        layoutTextField.setText("item_");
        packageTextField.setText(packageName);

        inUpdate.set(false);
        titleLabel.setFont(titleLabel.getFont().deriveFont(25F));

    }

    private void updateLayoutName() {
        if (inUpdate.get()) {
            return;
        }
        itemUpdateFromInput = true;
        if (layoutUpdateFromInput) {
            return;
        }
        inUpdate.set(true);
        layoutTextField.setText(WordCoverHelperKt.camel2Underline(itemTextField.getText()));
        inUpdate.set(false);
    }

    private void updateItemName() {
        if (inUpdate.get()) {
            return;
        }
        layoutUpdateFromInput = true;
        if (itemUpdateFromInput) {
            return;
        }
        inUpdate.set(true);
        itemTextField.setText(WordCoverHelperKt.underline2Camel(layoutTextField.getText()));
        inUpdate.set(false);
    }

    public String getItemName() {
        return itemTextField.getText();
    }

    public String getLayoutName() {
        return layoutTextField.getText();
    }

    public String getPackageName() {
        return packageTextField.getText();
    }

    public String getFullName() {
        return packageTextField.getText() + "." + itemTextField.getText();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        groupPanel = new JPanel();
        groupPanel.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        titleLabel = new JLabel();
        titleLabel.setText("生成 DataItem");
        groupPanel.add(titleLabel, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        itemLabel = new JLabel();
        itemLabel.setText("DataItem Name :");
        groupPanel.add(itemLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        itemTextField = new JTextField();
        groupPanel.add(itemTextField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        layoutLabel = new JLabel();
        layoutLabel.setText("Layout name :");
        groupPanel.add(layoutLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        layoutTextField = new JTextField();
        groupPanel.add(layoutTextField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        packageLabel = new JLabel();
        packageLabel.setText("Package Name :");
        groupPanel.add(packageLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        packageTextField = new JTextField();
        groupPanel.add(packageTextField, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return groupPanel;
    }

}
